name: ci

on:
  pull_request:
    branches:
      - "master"

jobs:
  build-docker:
    runs-on:
      labels: ASUS-MRKOMUGIKO
    steps:
      # Fetch pr or pushed code from github
      - name: Checkout
        uses: actions/checkout@v3
      # Login to docker hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      #setup
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      # Buid docker image
      - name: Build Docker image
        run: |
          docker buildx build -t ${{ env.IMAGE_TAG }} -f ./SignalRApp/Server/Dockerfile . --load
          docker images -a